## Customize the test machine
machine:  
  java:
    version: oraclejdk8
    environment:
            ANDROID_HOME: /usr/local/android-sdk-linux
            ANDROID_BUILD_TOOLS: 27
            APPLICATION_ID: com.example.android.medmanagerapplication


## Customize checkout
checkout:
  post:
    - git submodule sync
    - git submodule update --init # use submodules

## Customize dependencies
dependencies:
  pre:
    # workaround for "failed to find Build Tools revision xx"
    # https://discuss.circleci.com/t/android-build-tools-23-0-2-not-available/455/3
    - echo y | android update sdk --no-ui --all --filter platform-tools,tools,extra-android-m2repository,extra-google-m2repository,android-23
    - echo y | android update sdk --no-ui --all --filter build-tools-23.0.3

  override:
    - sudo ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies 
